version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DoYourLoginEuOdeioReact2x
    volumes:
      - sqlserver-2-data:/var/opt/mssql
    ports:
      - "1432:1433"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8025:8025"
volumes:
  sqlserver-2-data: