version: '3'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DoYourLoginEuOdeioReact2x
    volumes:
      - sqlserver-data:/var/opt/mssql
    ports:
      - "1433:1433"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8025:8025"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: SeDerErroEscreveAwait
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
volumes:
  sqlserver-data:
  mongodb-data: